# 자동으로 수정되지 않는 규칙을 활성화합니다.
# 기본적으로 알파벳 순서대로 정렬합니다.
# 원티드 가이드이면서 비활성화한 규칙이나 옵션에 대한 이유는 wiki에 정리되어 있습니다.
# xcode에서는 자동 수정되지 않는 규칙만 위반 여부를 체크합니다. (autocorrect 옵션을 제외했기 때문)
# 대신, pre-commit 파일에서 커밋을 시도할 때 자동 수정되는 규칙을 체크해 자동수정을 수행합니다.

# 린트 과정에서 무시할 파일 경로
excluded:
  - Carthage
  - fastlane
  - frameworks
  - Pods

# wantedTests 디렉토리 내 파일들을 위한 별도의 설정파일이 디렉토리내에 있습니다.

whitelist_rules:
  ######## opt_in_rules ########
  - convenience_type
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  #- trailing_closure #비활성화
  ## 자동 수정되는 규칙 ##
  - closure_spacing
  - empty_parameters
  - implicit_return
  - operator_usage_whitespace
  - redundant_type_annotation
  - return_arrow_whitespace
  - syntactic_sugar
  #- trailing_newline #Xcode에서 자동으로 추가
  #- trailing_whitespace #Xcode에서 설정하면 자동 수정됨
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - vertical_whitespace
  - void_return
  ######## disabled_rules ########
  - control_statement
  - identifier_name
  - implicit_getter
  - large_tuple
  #- line_length
  - multiple_closures_with_trailing_closure
  #- redundant_string_enum_value #비활성화
  - type_name
  - unused_optional_binding
  ## 자동 수정되는 규칙 ##
  - colon
  - empty_parentheses_with_trailing_closure
  - mark
  - no_space_in_method_call

# 개별적으로 룰 커스터마이징
identifier_name:
  min_length: 1
  max_length: 60
  allowed_symbols: [_]

large_tuple:
  warning: 3
  error: 4

line_length:
  warning: 110
  error: 110
  ignores_urls: true
  ignores_comments: true

type_name:
    min_length: 2
    max_length: 60
    allowed_symbols: [_]
